name: tennis
channels:
- conda-forge
- defaults
- pytorch
dependencies:
- python=3.6
- matplotlib
- numpy
- pandas
- scipy
- pytorch=0.4.1
- torchvision
- cookiecutter
- opencv
- ipython
- tqdm
- scikit-learn
- jupyter
- nb_conda
- scikit-image
- pip:
  - git+https://github.com/hmmlearn/hmmlearn.git
  - pytesseract
