name: tennis
channels:
- conda-forge
- defaults
- pytorch
dependencies:
- python=3.6
- matplotlib
- numpy
- pandas
- scipy
- pytorch
- torchvision
- cookiecutter
- requests
- ignite
- opencv
- ipython
- tqdm
- scikit-learn
- jupyter
- nb_conda
- pymc3
- scikit-image
- umap-learn
